### ISSUE TITLE
Log Warning: use of out-of-scope local JSONStreaming::filt deprecated

### ISSUE THREAD

**Issue by gwsales** [corelight/json-streaming-logs#10]
warning in /usr/local/zeek/spool/installed-scripts-do-not-touch/site/packages/./json-streaming-logs/./main.zeek, line 135: use of out-of-scope local JSONStreaming::filt deprecated; move declaration to outer scope
```
		{
		Log::add_filter(stream, filt);
		}
```

Not sure what this issue or error is, but when running zeek with this plugin I get a single line entry in stderr.log that says this is deprecated.

Looks like the issue is related to how `filt` is defined here but I can't really see anything wrong with it.
```
for ( [stream, filt] in new_filters )
```

**Comment by gwsales** [comment]
This might fix the issue, but I don't really know what other impact this could have:
```
const filt = Log::get_filter(stream, filter_name) &redef;
```

**Comment by andrewthad** [comment]
Try this. Replace this part at the bottom:

	for ( [stream, filt] in new_filters )
		{
		Log::add_filter(stream, filt);
		}
	}

With this:

	for ( [stream, theFilter] in new_filters )
		{
		Log::add_filter(stream, theFilter);
		}
	}

The warning happens because it's mad that the binder `filt` was reused. Variable scope does not actually appear to impact the way a context is formed during evaluation in the zeek programming language. It appears to be more of a hint.
