### ISSUE TITLE
File match glob duplicates events on rotation

### ISSUE THREAD

**Issue by dspruell-s01** [corelight/json-streaming-logs#5]
From the README:

> Logs are named in such a way that a glob in your log shipper configuration should be able to easily match all of the logs. Each log will have a prefix of json_streaming_ so that the http log would have the full name of json_streaming_http.log

In some configurations the typical wildcard match on the json_streaming_ logs results in duplicate event collection by the shipper. For a given event, the log is read once in the current output file, and then one time additionally for each rotated log file. It seems like by default [rotate_logs](https://github.com/corelight/json-streaming-logs/blob/master/scripts/main.bro#L42) will create at least one rotated file (.1.log), even if `JSONStreaming::extra_files` is set to 0.

This shows a unique event that only occurred once but is picked up repeatedly at each rotation interval by the shipper (in this case Fluentd/td-agent):

![image](https://user-images.githubusercontent.com/42474668/91622448-ffb39680-e94b-11ea-9b04-cdb16174e9b4.png)

The Fluentd configuration, with the `path` option wildcard matching the log files:

```
<source>
    @type tail
    @id zeek_json
    @label @zeek
    tag zeek.*
    path /nsm/zeek/logs/current/json_streaming_*.log
    pos_file /var/log/td-agent/tmp/zeek_json.pos
    <parse>
        @type json
    </parse>
</source>
```

What is the best course of action here? Is this a case where json-streaming-logs should support giving the output file a different file name that can be uniquely matched by the given glob (and not the extra files), or is this a situation that a log shipper should be able to handle better? Fluentd [documentation](https://docs.fluentd.org/input/tail) does state:

> You should not use * with log rotation because it may cause the log duplication. In this case, you should separate in_tail plugin configuration.

...but at the same time, Zeek outputs several logs and it's not clear up front which log file may appear at some point, so a glob approach is probably the most correct. If the plugin could be guaranteed to output a single file that wouldn't be picked up again at rotation, that seems the most predictable.

**Comment by sethhall** [comment]
Master (and tag v2.0) currently support the ability to set JSONStreaming::extra_files to 0.  Regarding the problem with the pos setting, I'm not really sure what to do yet.  Unfortunately many of these log shippers don't have exactly the right combination of settings for Zeek and if we created a log writer that wrote out a single file it would cause some amount of overhead to the whole system.

It would be nice if the pos files could be auto created for any files being followed, but I just checked fluentd and it doesn't seem to have that ability.

I would recommend checking out fluent bit.  It looks like it's tail input module would work the way you want because you specify a single offset database for the pattern and it'll track all of the files that it's monitoring in there.

**Comment by dspruell-s01** [comment]
On input from @sethhall and the Fluentd dev team, initial testing of a Fluentd release candidate seems to have positive results. This brings the addition of a new `follow_inodes` parameter to in_tail input plugin.

```
<source>
    @type tail
    @id zeek_json
    @label @zeek
    tag zeek.*
    path /nsm/zeek/logs/current/json_streaming_*.log
    pos_file /var/log/fluent/tmp/zeek_json.pos
    follow_inodes true
    <parse>
        @type json
    </parse>
</source>
```

https://groups.google.com/g/fluentd/c/spWNMv13VBc
